version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: json_app
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: json_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ./src:/app/src:ro
      - ./.env:/app/.env:ro
    environment:
      APP_NAME: "Post Sync App"
      APP_HOST: "0.0.0.0"
      APP_PORT: 8000
      HTTP_TIMEOUT: 10
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: json_app
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      SQLALCHEMY_ECHO: "false"
      BASE_URL: "https://jsonplaceholder.typicode.com"
      SYNC_INTERVAL_HOURS: 24

volumes:
  pg_data:
